import { ProductModel } from './product.model';

export const Products: ProductModel[] = [
  {
    id: 1,
    name: 'Red Jalapeño — Fresh',
    price: 3.99,
    description: 'Medium heat, crisp flavor, perfect for salsas and stuffing. Sold in 250g packs.',
    imageUrl: '/Assests/Images/Red-Jalapeno-Fresh.jpg',
    rating: 4.5,
    availability: true,
    itemsInInventory: 6,
  },
  {
    id: 2,
    name: 'Dark Chocolate with Chipotle flakes',
    price: 6.99,
    description: 'Rich dark chocolate with a spicy chipotle kick.',
    imageUrl: '/Assests/Images/Dark-Chocolate-Chipotle.jpg',
    rating: 4.8,
    availability: true,
    itemsInInventory: 2,
  },
  {
    id: 3,
    name: 'Habanero Mix Pack',
    price: 5.49,
    description:
      'A vibrant trio of yellow, red, and green habaneros. Intense fruity heat. Sold in 250g packs.',
    imageUrl: '/Assests/Images/Habanero-Mix.jpg',
    rating: 4.7,
    availability: true,
    itemsInInventory: 3,
  },
  {
    id: 4,
    name: 'Reaper Hot Sauce',
    price: 9.99,
    description: 'A fiery sauce made from Carolina Reapers. Fruity, smoky, dangerously hot.',
    imageUrl: '/Assests/Images/Reaper-Hot-Sauce.jpg',
    rating: 4.6,
    availability: true,
    itemsInInventory: 8,
  },
  {
    id: 5,
    name: 'Pepper Grow Kit',
    price: 12.99,
    description: 'Includes seeds, soil pods, and instructions to grow your own chili plants.',
    imageUrl: '/Assests/Images/Grow-Kit.jpg',
    rating: 4.9,
    availability: true,
    itemsInInventory: 1,
  },
  {
    id: 6,
    name: 'Bird’s Eye Chili',
    price: 4.29,
    description: 'Small but mighty peppers used in Southeast Asian cuisine. Sold in 30g bag.',
    imageUrl: '/Assests/Images/Bird’s-Eye-Chili.jpg',
    rating: 4.4,
    availability: true,
    itemsInInventory: 20,
  },
];
